spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        registration:
          github:
            clientId:
              b15c524ec6af71a50550
            clientSecret:
              e331fb250208e6eea7b8e0867292afd4e43f958e
server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8079/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"