services:
  movie-db-postgres:
    container_name: postgres-movie-db
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0
    restart: always
    ports:
      - 8078:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    entrypoint: /opt/keycloak/bin/kc.sh start-dev