services:
  api-gateway-postgres:
    container_name: postgres-api-gateway
    image: postgres:15-alpine
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  movie-db-postgres:
    container_name: postgres-movie-db
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres