server:
  port: 8080

spring:
  application:
    name: film-db
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    drop-first: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8079/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"